version: '3'
services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mock/mappings:/home/wiremock/mappings
      - ./mock/__files:/home/wiremock/__files